<?php

namespace app\modules\admin\controllers;

use app\common\filters\LoginFilter;

class BaseController extends \yii\web\Controller
{
    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $default = [
            /*'login' => [
                'class' => LoginFilter::className(),
                'failUrl' => '/login'
            ]*/
        ];

        $append = $this->appendBehaviors();

        return array_merge($parent,$default,$append);
    }

    /**
     * 追加行为
     * @return array
     * @author: liuFangShuo
     */
    public function appendBehaviors()
    {
        return [];
    }
}
