<?php

namespace app\modules\admin\controllers;

use app\common\filters\LoginFilter;
use app\common\filters\PermissionFilter;
use Yii;
use yii\web\Response;

class BaseController extends \yii\web\Controller
{
    public $enableCsrfValidation = false;
    protected $_user;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_user = \Yii::$app->user->identity;

        //页面渲染使用
        $view = \Yii::$app->view;
        $view->params['userInfo'] = $this->_user;
    }

    /**
     * 过滤器
     * @return array
     * @author: liuFangShuo
     */
    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $default = [
            'login' => [
                'class' => LoginFilter::className(),
                'failUrl' => '/login'
            ],
            'permission' => [
                'class' => PermissionFilter::className(),
                'except' => ['login', 'admin', 'admin/index/index'],
                'failUrl' => '/login'
            ],
        ];

        $append = $this->appendBehaviors();

        return array_merge($parent,$default,$append);
    }

    /**
     * 追加行为
     * @return array
     * @author: liuFangShuo
     */
    public function appendBehaviors()
    {
        return [];
    }

    protected function ajaxReturn($data = array(), $code = 0, $message = '')
    {
        $data = array(
            'data' => $data,
            'code' => $code,
            'message' => $message
        );

        return \Yii::createObject([
            'class' => 'yii\web\Response',
            'format' => Response::FORMAT_JSON,
            'data' => $data
        ]);
    }
}
