<?php

namespace app\modules\admin\controllers;

use app\common\filters\LoginFilter;
use Yii;

class BaseController extends \yii\web\Controller
{
    protected $_user;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_user = \Yii::$app->user->identity;

        //页面渲染使用
        $view = \Yii::$app->view;
        $view->params['userInfo'] = $this->_user;
    }

    /**
     * 过滤器
     * @return array
     * @author: liuFangShuo
     */
    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $default = [
            'login' => [
                'class' => LoginFilter::className(),
                'failUrl' => '/login'
            ]
        ];

        $append = $this->appendBehaviors();

        return array_merge($parent,$default,$append);
    }

    /**
     * 追加行为
     * @return array
     * @author: liuFangShuo
     */
    public function appendBehaviors()
    {
        return [];
    }
}
