<?php

namespace app\models\ar;

use Yii;

/**
 * This is the model class for table "zc_department".
 *
 * @property int $id 员工部门id
 * @property string $name
 * @property int $create_time
 * @property int $update_time
 * @property string $code 编号
 * @property int $is_deleted 是否删除
 * @property int $num 人数
 */
class DepartmentAR extends \app\models\ar\BaseAR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zc_department';
    }

    public function scenarios()
    {
        $parent = parent::scenarios();
        $self = [
            'create' => ['name', 'code'],
            'update' => ['name', 'code'],
        ];

        return  array_merge($parent,$self); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code'], 'required', 'on'=>'default'],
            [['is_deleted', 'num'], 'integer', 'on'=>'default'],
            [['name'], 'string', 'max' => 32],
            [['code'], 'string', 'max' => 16],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
            'code' => 'Code',
            'is_deleted' => 'Is Deleted',
            'num' => 'Num',
        ];
    }

    /**
     * @author: liuFangShuo
     */
    public function saveDepartment()
    {
        //查找一下
        if ($this->getScenario() == 'create') {
            $model = new static();
            $model->create_time = time();
        }

        if($this->getScenario() == 'update') {
            $model = static::findOne(['id' => $this->id, 'is_deleted' => STATUS_FALSE]);

            if (empty($model)) {
                $this->addError('title','不存在此id');
                return false;
            }
        }

        $model->name = $this->name;
        $model->code = $this->code;
        $model->update_time = time();

        if(!$model->save(false)){
            $this->addError('code', '网络问题，稍后重试');
            return false;
        } else {
            return true;
        }
    }
}
