<?php

namespace app\models\ar;

use Yii;

/**
 * This is the model class for table "zc_param".
 *
 * @property int $id 参数表ID
 * @property int $type 类别
 * @property string $json 数据
 * @property int $create_time
 * @property int $update_time
 */
class ParamAR extends \app\models\ar\BaseAR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zc_param';
    }

    public function scenarios()
    {
        $parent = parent::scenarios();
        $self = [
            'create' => ['type', 'json'],
            'update' => ['type', 'json'],
        ];

        return  array_merge($parent,$self); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'json'], 'required', 'on'=>'default'],
            [['type'], 'integer', 'on'=>'default'],
            [['json'], 'string', 'max' => 2048, 'on'=>'default'],
            ['type', 'in', 'range' => array_keys(Yii::$app->params['param_type']), 'message'=>'参数不存在', 'on' => ['create', 'update']],
            [['json', 'type'], 'required', 'message' => '不能为空', 'on' => ['create', 'update']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'json' => 'Json',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
        ];
    }


}
