<?php

namespace app\models\ar;

use Yii;

/**
 * This is the model class for table "zc_process".
 *
 * @property int $id 质检流程
 * @property int $type 0为质检项、1为质检项组
 * @property string $name 质检流程名称
 * @property int $is_deleted
 * @property int $create_time
 * @property int $update_time
 */
class ProcessAR extends \app\models\ar\BaseAR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zc_process';
    }

    public function scenarios()
    {
        $parent = parent::scenarios();
        $self = [
            'create' => ['type', 'name'],
            'update' => ['type', 'name'],
        ];

        return  array_merge($parent,$self); // TODO: Change the autogenerated stub

    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'is_deleted'], 'integer', 'on'=>'default'],
            [['name'], 'string', 'max' => 16, 'on' => ['default']],
            [['name', 'type'], 'required', 'message' => '不能为空', 'on' =>['create', 'update']],
            ['name', 'string', 'length' => [1, 16], 'tooLong'=>'最大长度为16个汉字', 'on' => ['create','update']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'name' => 'Name',
            'is_deleted' => 'Is Deleted',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
        ];
    }

    /**
     * 保存检查流程
     * @return bool
     * @author: liuFangShuo
     */
    public function saveProcess()
    {
        //查找一下
        if ($this->getScenario() == 'create') {
            $model = new static();
        }

        if($this->getScenario() == 'update') {
            $model = static::findOne(['id' => $this->id, 'is_deleted' => STATUS_FALSE]);

            if (empty($model)) {
                $this->addError('name','不存在此id');
                return false;
            }
        }

        $model->name = $this->name;
        $model->type = $this->type;

        if(!$model->save(false)){
            $this->addError('name', '网络问题，稍后重试');
            return false;
        } else {
            return true;
        }
    }
}
