<?php

namespace app\models\ar;

use Yii;

/**
 * This is the model class for table "zc_role".
 *
 * @property int $id
 * @property string $name 角色名称
 * @property int $permission_num 拥有权限数量
 * @property int $user_num 用户数量
 * @property int $is_deleted
 * @property int $create_time 创建时间
 * @property int $update_time 更新时间
 */
class RoleAR extends \app\models\ar\BaseAR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zc_role';
    }

    /**
     * 场景
     * @author: liuFangShuo
     */
    public function scenarios()
    {
        $parent = parent::scenarios();
        $self = [
            'create' => ['name'],
            'update' => ['name'],
        ];

        return  array_merge($parent,$self); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['permission_num', 'user_num', 'is_deleted'], 'integer', 'on' => 'default'],
            [['name'], 'string', 'max' => 32, 'on' => 'default'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'permission_num' => 'Permission Num',
            'user_num' => 'User Num',
            'is_deleted' => 'Is Deleted',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
        ];
    }

    /**
     * 保存角色
     * @author: liuFangShuo
     */
    public function saveRole()
    {
        //查找一下
        if ($this->getScenario() == 'create') {
            $model = new static();
        }

        if($this->getScenario() == 'update') {
            $model = static::findOne(['id' => $this->id, 'is_deleted' => STATUS_FALSE]);

            if (empty($model)) {
                $this->addError('name','不存在此id');
                return false;
            }
        }

        $model->name = $this->name;

        if(!$model->save(false)){
            $this->addError('name', '网络问题，稍后重试');
            return false;
        } else {
            return true;
        }
    }
}
