<?php

namespace app\models\ar;

use Yii;

/**
 * This is the model class for table "zc_user_group".
 *
 * @property int $id ID
 * @property string $name 用户组
 * @property int $station_id 工位id
 * @property int $is_deleted 是否删除
 * @property int $create_time 创建时间
 * @property int $update_time 更新时间
 */
class UserGroupAR extends \app\models\ar\BaseAR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zc_user_group';
    }

    /**
     * 场景
     * @return array
     * @author: liuFangShuo
     */
    public function scenarios()
    {
        $parent = parent::scenarios();
        $self = [
            'create' => ['name', 'station_id'],
            'update' => ['name', 'station_id'],
        ];

        return  array_merge($parent,$self); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['station_id'], 'required', 'on' => 'default'],
            [['station_id', 'is_deleted'], 'integer','on' => 'default'],
            [['name'], 'string', 'max' => 16, 'on' => 'default'],
            [['name', 'station_id'], 'required', 'message' => '不能为空', 'on' => ['create', 'update']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'station_id' => 'Station ID',
            'is_deleted' => 'Is Deleted',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
        ];
    }

    /**
     * 员工组
     * @author: liuFangShuo
     */
    public function saveStaffGroup()
    {
        //查找一下
        if ($this->getScenario() == 'create') {
            $model = new static();

        }

        if($this->getScenario() == 'update') {
            $model = static::findOne(['id' => $this->id, 'is_deleted' => STATUS_FALSE]);

            if (empty($model)) {
                $this->addError('title','不存在此id');
                return false;
            }
        }

        $model->name = $this->name;
        $model->station_id = $this->station_id;

        if(!$model->save(false)){
            $this->addError('code', '网络问题，稍后重试');
            return false;
        } else {
            return true;
        }
    }
}
