<?php

namespace app\models\ar;

use Yii;

/**
 * This is the model class for table "zc_workshop".
 *
 * @property int $id 车间id
 * @property string $name 车间名称
 * @property string $code 编号
 * @property int $pid 上一车间id
 * @property int $sort 位置
 * @property int $is_deleted 是否删除
 * @property int $create_time
 * @property int $update_time
 */
class WorkshopAR extends \app\models\ar\BaseAR
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zc_workshop';
    }


    public function scenarios()
    {
        $parent = parent::scenarios();
        $self = [
            'create' => ['name', 'code', 'pid', 'sort'],
            'update' => ['name', 'code', 'pid', 'sort'],
        ];

        return  array_merge($parent,$self); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pid', 'sort'], 'required', 'on' => 'default'],
            [['pid', 'sort'], 'integer', 'on' => 'default'],
            [['name'], 'string', 'max' => 16, 'on' => ['create','update', 'default']],
            [['code'], 'string', 'max' => 32, 'on' => ['create','update', 'default']],
            [['name', 'code', 'pid'], 'required', 'message' => '不能为空', 'on' =>['create', 'update']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'code' => 'Code',
            'pid' => 'Pid',
            'sort' => 'Sort',
            'is_deleted' => 'Is Deleted',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
        ];
    }

    /**
     * 保存车间信息
     * @author: liuFangShuo
     */
    public function saveWorkshop()
    {
        //查找一下
        $model = static::findOne(['code' => $this->code, 'is_deleted' => STATUS_FALSE]);

        //创建时必须不能存在
        if($this->getScenario() == 'create' && !empty($model)){
            $this->addError('code', '车间编号已存在');
            return false;
        }

        //更新时必须存在
        if($this->getScenario() == 'update' && empty($model)){
            $this->addError('name', '车间不存在');
            return false;
        }

        if(empty($model)){
            $model = new static();
            $model->create_time = time();
        }

        //查找一下上一级车间
        $pws = static::findOne(['id' => $this->pid, 'is_deleted' => STATUS_FALSE]);

        $model->name = $this->name;
        $model->code = $this->code;
        $model->pid = $this->pid;
        $model->sort = $pws->sort + 1;
        $model->update_time = time();

        if(!$model->save(false)){
            $this->addError('code', '网络问题，稍后重试');
            return false;
        } else {
            return true;
        }
    }
}
