<?php
/**
 * Created by liuFangShuo.
 * User: lfs
 * Date: 2018/3/16
 * Time: 14:30
 */

namespace app\common\filters;
use Yii;

class PermissionFilter extends BaseFilter
{
    /**
     * 操作之前
     * @param \yii\base\Action $action
     * @return bool
     * @author: liuFangShuo
     */
    public function beforeAction($action)
    {
        //根据用户查询一下对应的权限


        if(Yii::$app->user->isGuest){
            $this->fail('/login');
            return false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 操作之后
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return mixed
     * @author: liuFangShuo
     */
    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}