<?php
/**
 * Created by liuFangShuo.
 * User: lfs
 * Date: 2018/3/16
 * Time: 14:30
 */

namespace app\common\filters;
use app\models\ar\UserRoleAR;
use Yii;

class PermissionFilter extends BaseFilter
{
    private $_user = null;
    /**
     * 操作之前
     * @param \yii\base\Action $action
     * @return bool
     * @author: liuFangShuo
     */
    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
            $this->fail('/login');
            return false;
        }

        $this->_user = Yii::$app->user->identity;

        //超管
        if($this->_user->isSuperAdmin()){
            return true;
        }

        //获取拥有的权限
        $pathArr = $this->_user->getUserPermission();

        if (empty($pathArr)) {
            $this->fail();
            return false;
        }

        //获取当前url
        $path = Yii::$app->request->getUrl();

        if (!in_array($path, $pathArr)) {
            $this->fail();
            return false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 操作之后
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return mixed
     * @author: liuFangShuo
     */
    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}